name: Wilson Page
description: "Wilson is a front-end engineer in search of a new challenge."
url: http://wilsonpage.co.uk
permalink: /:title/
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: pygments
exclude: [
  'components',
  'node_modules',
  'GruntFile.js',
  'package.json'
]
